name: "StorageClass builder"
on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: '${{ github.token }}'
      - name: Build storageclass.info
        run: |
          sudo apt install -y npm
          npm install
          npm run build
      - name: Upload storageclass.info
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /
          local-dir: ./dist/
